# Generated by Django 4.2.10 on 2024-02-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalAdopter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalmodel',
            name='image',
            field=models.ImageField(max_length=144, null=True, upload_to=''),
        ),
    ]
