# Generated by Django 4.2.10 on 2024-03-05 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalAdopter', '0003_animalmodel_contact_alter_animalmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalmodel',
            name='name',
            field=models.CharField(default='', max_length=280),
        ),
    ]
