# Generated by Django 4.2.10 on 2024-03-25 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalAdopter', '0004_animalmodel_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=280)),
                ('age', models.CharField(max_length=280)),
                ('gender', models.CharField(max_length=280)),
                ('location', models.CharField(max_length=280)),
                ('contact', models.CharField(default='', max_length=280)),
                ('isShelter', models.CharField(default='', max_length=280)),
            ],
        ),
    ]
