# Generated by Django 4.2.11 on 2024-04-08 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalAdopter', '0005_alter_animalmodel_specialneeds'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalmodel',
            name='specialOne',
            field=models.CharField(default='false', max_length=280),
        ),
        migrations.AddField(
            model_name='animalmodel',
            name='specialThree',
            field=models.CharField(default='false', max_length=280),
        ),
        migrations.AddField(
            model_name='animalmodel',
            name='specialTwo',
            field=models.CharField(default='false', max_length=280),
        ),
    ]
