# Generated by Django 4.2.10 on 2024-03-25 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalAdopter', '0005_usermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='isShelter',
            field=models.CharField(default='no', max_length=280),
        ),
    ]
