# Generated by Django 5.0.2 on 2024-04-05 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animalAdopter', '0005_alter_animalmodel_specialneeds'),
        ('animalAdopter', '0006_alter_usermodel_isshelter'),
    ]

    operations = [
    ]
