# Generated by Django 5.0.2 on 2024-04-08 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animalAdopter', '0006_animalmodel_specialone_animalmodel_specialthree_and_more'),
        ('animalAdopter', '0007_merge_20240405_2016'),
    ]

    operations = [
    ]
