# Generated by Django 4.2.11 on 2024-04-16 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('animalAdopter', '0008_merge_20240408_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='age',
            field=models.CharField(default='', max_length=280),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='gender',
            field=models.CharField(default='', max_length=280),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='location',
            field=models.CharField(default='', max_length=280),
        ),
    ]
