# Generated by Django 4.2.10 on 2024-04-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalAdopter', '0008_merge_20240408_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalmodel',
            name='specialNeeds',
            field=models.CharField(default='', max_length=280),
        ),
    ]
