# Generated by Django 4.2.10 on 2024-04-17 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animalAdopter', '0008_merge_20240408_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animalmodel',
            name='image',
        ),
        migrations.CreateModel(
            name='AnimalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='animal_images')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='animalAdopter.animalmodel')),
            ],
        ),
    ]
