# Generated by Django 5.0.2 on 2024-04-17 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animalAdopter', '0009_animalmodel_specialneeds'),
        ('animalAdopter', '0009_usermodel_user_alter_usermodel_age_and_more'),
    ]

    operations = [
    ]
