# Generated by Django 4.2.10 on 2024-04-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalAdopter', '0009_remove_animalmodel_image_animalimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animalimage',
            name='animal',
        ),
        migrations.AddField(
            model_name='animalmodel',
            name='images',
            field=models.ManyToManyField(to='animalAdopter.animalimage'),
        ),
    ]
