# Generated by Django 4.2.11 on 2024-04-19 20:31

import animalAdopter.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('animalAdopter', '0010_merge_20240417_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalmodel',
            name='user',
            field=models.ForeignKey(default=animalAdopter.models.get_default_user, on_delete=django.db.models.deletion.CASCADE, related_name='animals', to=settings.AUTH_USER_MODEL),
        ),
    ]
