# Generated by Django 3.2.25 on 2024-04-29 19:30

import animalAdopter.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalAdopter', '0011_animalmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalmodel',
            name='image2',
            field=models.ImageField(max_length=144, null=True, upload_to=animalAdopter.models.animal_image_upload),
        ),
        migrations.AddField(
            model_name='animalmodel',
            name='image3',
            field=models.ImageField(max_length=144, null=True, upload_to=animalAdopter.models.animal_image_upload),
        ),
        migrations.AddField(
            model_name='animalmodel',
            name='image4',
            field=models.ImageField(max_length=144, null=True, upload_to=animalAdopter.models.animal_image_upload),
        ),
        migrations.AddField(
            model_name='animalmodel',
            name='image5',
            field=models.ImageField(max_length=144, null=True, upload_to=animalAdopter.models.animal_image_upload),
        ),
    ]
