# Generated by Django 3.2.25 on 2024-04-29 19:32

import animalAdopter.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalAdopter', '0011_animalmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='image',
            field=models.ImageField(max_length=144, null=True, upload_to=animalAdopter.models.user_image_upload),
        ),
    ]
