# Generated by Django 3.2.25 on 2024-04-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalAdopter', '0011_animalmodel_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='animal_images')),
            ],
        ),
        migrations.RemoveField(
            model_name='animalmodel',
            name='image',
        ),
        migrations.AddField(
            model_name='animalmodel',
            name='image',
            field=models.ManyToManyField(to='animalAdopter.AnimalImage'),
        ),
    ]
