# Generated by Django 3.2.25 on 2024-05-05 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animalAdopter', '0012_auto_20240429_1930'),
        ('animalAdopter', '0012_usermodel_image'),
    ]

    operations = [
    ]
