# Generated by Django 3.2.25 on 2024-05-07 01:22

import animalAdopter.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalAdopter', '0014_auto_20240505_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='image5',
        ),
        migrations.AddField(
            model_name='animalmodel',
            name='adoptForm',
            field=models.FileField(max_length=144, null=True, upload_to=animalAdopter.models.animal_adopt_form),
        ),
    ]
