# Generated by Django 3.2.25 on 2024-05-06 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animalAdopter', '0014_auto_20240505_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='image5',
        ),
    ]
