# Generated by Django 3.2.25 on 2024-05-13 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalAdopter', '0015_auto_20240507_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalmodel',
            name='breed',
            field=models.CharField(default='', max_length=280),
        ),
    ]
